### ISSUE TITLE
Multiple-choice radio selector

### ISSUE THREAD

**Issue by datawithdev** [baobabKoodaa/cloudbite#2]
Atte, 
Great job with the cards. What would it take to add ability to select from multiple choice questions? Similar to AWS certifications.

**Comment by baobabKoodaa** [comment]
Thanks! It would take a lot of work to change this to multiple-choice format, because both the content and the UI would need significant changes. The content was designed for flashcards, so in most cases the question format is not applicable to just adding 3 false answers per every right answer; the questions and "right answers" would need to be changed as well. And the current UI is built around the central flashcard, so it would be a significant rework to modify the UI for multiple-choice format.
